[phases.setup]
nixPkgs = ['nodejs-20_x', 'npm-10_x']

[phases.install]
cmds = ['cd apps/backend', 'npm install --only=production']

[phases.build] 
cmds = ['cd apps/backend', 'npm run build']

[start]
cmd = 'cd apps/backend && npm run start:prod'

[variables]
NODE_ENV = 'production'