[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/backend/Dockerfile"

[deploy]
startCommand = "node dist/main"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
variables = { NODE_ENV = "production", PORT = "3001" }

[environments.staging]
variables = { NODE_ENV = "staging", PORT = "3001" }

[[services]]
name = "investie-backend"
source = "apps/backend"

[[services.environments.production]]
variables = { NODE_ENV = "production" }

[[services.healthchecks]]
path = "/health"
interval = 30