services:
  - type: web
    name: investie-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm run build:packages && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CLAUDE_API_KEY
        sync: false
      - key: SERPAPI_API_KEY
        sync: false  
      - key: FRED_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false